### ISSUE TITLE
Nette Tester with TeamCity output format not detected

### ISSUE THREAD

**Issue by castamir** [jiripudil/intellij-nette-tester#10]
I've installed it via
```json

    "require-dev": {
        "nette/tester": "dev-feature/teamcity-output"
    },
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/jiripudil/tester"
        }
    ]
```

and `composer update --prefer-dist`

composer downloaded your forked version, but plugin still shows this error. Restart didn't help. I'm running PS v10.0.3 on Windows 10

![tester-plugin](https://cloud.githubusercontent.com/assets/1245190/13563948/3d55496c-e446-11e5-907d-798b65b861d1.png)

**Comment by kerleba** [comment]
I have the same problem. I also installed it via composer. W10 - PS v. 10.0.3.
![image](https://cloud.githubusercontent.com/assets/11274423/13570015/df7af85c-e46b-11e5-9ecb-09b583861d93.png)

**Comment by zarubik** [comment]
I have the same problem. Version: 1.0-alpha2, W10 - PS v. 2016.1.2

**Comment by peterpp** [comment]
Any progress? The same problem on Mac OS X 10.11.5, PhpStorm 2016.1.2, Nette Tester 1.0-alpha2.

**Comment by peterpp** [comment]
I upgraded PhpStorm to 2016.2 and plugin started  to work. It is able to detect Nette Tester with TeamCity now.

**Comment by jiripudil** [comment]
Composer does funny things to vendor binaries on Windows, so you need to point the Tester executable to the actual PHP script (`vendor/nette/tester/src/tester`). I've updated the README with a notice for Windows users
