### ISSUE TITLE
Incorrect time duration

### ISSUE THREAD

**Issue by mrtnzlml** [jiripudil/intellij-nette-tester#11]
Hi, I noticed that measured time is wrong compared to CLI (but it's obvious it doesn't work even without CLI).
- without `@multiple` and with `@testCase` annotations **15s 63ms** (but it should be ~1.6s)
- with `@multiple` and with `@testCase` annotations **1m 56s 1m** (in CLI ~13.1s)

Does this plugin take into account `@multiple` and `@testCase` annotations?

**Comment by jiripudil** [comment]
See #6. I can't see a way around this issue at all :(

**Comment by mrtnzlml** [comment]
Oh, sorry. This is unfortunately quite a big issue for me because total time is sometimes important. Should I close this issue as well or should I wait? I really hope you'll figure it out somehow... :)
