### ISSUE TITLE
Better message when some tests are skipped

### ISSUE THREAD

**Issue by jkuchar** [jiripudil/intellij-nette-tester#22]
![image](https://cloud.githubusercontent.com/assets/133822/26551394/a57be314-4482-11e7-966f-f6a878c86789.png)

Now it says "Terminated" which does not provide any useful information.

What about something like

> **Tests passed** <small>*(14 has been skipped)*</small>

**Comment by jiripudil** [comment]
Oh, I see, that's a fuckup of TeamCity messages docs. It is, contrary to what is says, actually not enough to report the test as failed or ignored, `testFinished` must be sent as well. This will be an easy fix, thanks for the report @jkuchar 

That's for one part of the issue. The exact wording, however, is done on the IDE's side and there's nothing I can do about it, so "Test Results" will have to do. You can find the summary to the right of the progress bar:

<img width="667" alt="snimek obrazovky 2017-05-29 v 16 13 56" src="https://cloud.githubusercontent.com/assets/1042159/26552993/ea9ef2e0-4489-11e7-9d0f-5db56ecd6be1.png">
