### ISSUE TITLE
List of test methods for TestCases

### ISSUE THREAD

**Issue by SendiMyrkr** [jiripudil/intellij-nette-tester#29]
Is there some way how get in test results list of all test methods in TestCases?

**Comment by jiripudil** [comment]
What exactly do you have on mind?

Grouping the test methods under their test case the same way PHPUnit or JUnit plugins do? That is a tricky one as it needs the Tester's OutputHandler to provide information about the tests in a more structured manner; I'm planning to implement it as a part of #18, in one way or another

**Comment by SendiMyrkr** [comment]
Exactly what i mean. So i guess you can close it. Maybe you can add some comment with planning feature, i will not spam with ideas which you have in head already. :)

**Comment by jiripudil** [comment]
No worries, feel free to keep spamming me with ideas, the amount of feedback I've got from you is tremendous and much appreciated!

For convenience, I've added the list directly to #18; other ideas and plans are already outlined in issues since my head can't keep them all 😉
