### ISSUE TITLE
Undefined class constant 'SKIPPED'

### ISSUE THREAD

**Issue by peterpp** [jiripudil/intellij-nette-tester#33]
I've updated plugin from alpha.4 to beta.2 and changed

```
"require-dev": {
	"nette/tester": "dev-feature/teamcity-output"
},
```

to `"nette/tester": "@dev"`

Now, I get error:

Fatal error: Undefined class constant 'SKIPPED' in .../PhpStorm2017.1/intellij-nette-tester/setup.php on line 39

**Comment by jiripudil** [comment]
Duplicate of #30, in short: Nette Tester dev-master is not (yet?) supported. Please stick to 1.x stable release until it is resolved. Sorry for the inconvenience 🙁

**Comment by peterpp** [comment]
Today I'm really blind 🙈
