### ISSUE TITLE
Right click & run testcase / method

### ISSUE THREAD

**Issue by fprochazka** [jiripudil/intellij-nette-tester#8]
phpunit has support for running a single testcase from right-click menu

![snimek obrazovky porizeny 2016-02-28 19 39 12](https://cloud.githubusercontent.com/assets/158625/13381111/37642968-de53-11e5-92ae-c02c1fc48cc9.png)

more usefull might be running a single method, since running the whole file works exactly like running single testcase in phpunit

![snimek obrazovky porizeny 2016-02-28 19 40 34](https://cloud.githubusercontent.com/assets/158625/13381110/375c1872-de53-11e5-9ea7-01e6b3ad7f7e.png)

**Comment by jiripudil** [comment]
I'm closing this in favor of #2 and #9. Thank you :)
